version: '3.9'
services:
  evolution-api:
    container_name: evolution_api
    image: atendai/evolution-api:v2.1.1
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - evolution_instances:/evolution/instances
    networks:
      - evolution-net  # Usa a mesma rede que MySQL e Redis

volumes:
  evolution_instances:

networks:
  evolution-net:
    external: true 
