version: '3.8'

services:
  api:
    container_name: evolution_api
    image: atendai/evolution-api
    restart: always
    ports:
      - 8081:8080
    volumes:
      - evolution_instances:/evolution/instances
      - evolution_store:/evolution/store
    networks:
      - evolution-net
    command: ['node', './dist/src/main.js']
    expose:
      - 8080
    environment:
      SERVER_URL: http://localhost:8080
      CORS_ORIGIN: "*"
      CORS_METHODS: POST,GET,PUT,DELETE
      CORS_CREDENTIALS: "true"
      LOG_LEVEL: ERROR,WARN,DEBUG,INFO,LOG,VERBOSE,DARK,WEBHOOKS
      LOG_COLOR: "true"
      LOG_BAILEYS: error
      DEL_INSTANCE: "false"
      DEL_TEMP_INSTANCES: "true"
      STORE_MESSAGES: "true"
      STORE_MESSAGE_UP: "true"
      STORE_CONTACTS: "true"
      STORE_CHATS: "true"
      CLEAN_STORE_CLEANING_INTERVAL: 7200
      CLEAN_STORE_MESSAGES: "true"
      CLEAN_STORE_MESSAGE_UP: "true"
      CLEAN_STORE_CONTACTS: "true"
      CLEAN_STORE_CHATS: "true"
      DATABASE_ENABLED: "false"
      DATABASE_CONNECTION_URI: mongodb://root:root@mongodb:27017/?authSource=admin&readPreference=primary&ssl=false&directConnection=true
      DATABASE_CONNECTION_DB_PREFIX_NAME: evdocker
      DATABASE_SAVE_DATA_INSTANCE: "false"
      DATABASE_SAVE_DATA_NEW_MESSAGE: "false"
      DATABASE_SAVE_MESSAGE_UPDATE: "false"
      DATABASE_SAVE_DATA_CONTACTS: "false"
      DATABASE_SAVE_DATA_CHATS: "false"
      RABBITMQ_ENABLED: "false"
      RABBITMQ_URI: amqp://guest:guest@rabbitmq:5672
      RABBITMQ_EXCHANGE_NAME: evolution_exchange
      RABBITMQ_GLOBAL_ENABLED: "false"
      RABBITMQ_EVENTS_APPLICATION_STARTUP: "false"
      RABBITMQ_EVENTS_QRCODE_UPDATED: "true"
      RABBITMQ_EVENTS_MESSAGES_SET: "true"
      RABBITMQ_EVENTS_MESSAGES_UPSERT: "true"
      RABBITMQ_EVENTS_MESSAGES_UPDATE: "true"
      RABBITMQ_EVENTS_MESSAGES_DELETE: "true"
      RABBITMQ_EVENTS_SEND_MESSAGE: "true"
      RABBITMQ_EVENTS_CONTACTS_SET: "true"
      RABBITMQ_EVENTS_CONTACTS_UPSERT: "true"
      RABBITMQ_EVENTS_CONTACTS_UPDATE: "true"
      RABBITMQ_EVENTS_PRESENCE_UPDATE: "true"
      RABBITMQ_EVENTS_CHATS_SET: "true"
      RABBITMQ_EVENTS_CHATS_UPSERT: "true"
      RABBITMQ_EVENTS_CHATS_UPDATE: "true"
      RABBITMQ_EVENTS_CHATS_DELETE: "true"
      RABBITMQ_EVENTS_GROUPS_UPSERT: "true"
      RABBITMQ_EVENTS_GROUPS_UPDATE: "true"
      RABBITMQ_EVENTS_GROUP_PARTICIPANTS_UPDATE: "true"
      RABBITMQ_EVENTS_CONNECTION_UPDATE: "true"
      RABBITMQ_EVENTS_LABELS_EDIT: "true"
      RABBITMQ_EVENTS_LABELS_ASSOCIATION: "true"
      RABBITMQ_EVENTS_CALL: "true"
      RABBITMQ_EVENTS_TYPEBOT_START: "false"
      RABBITMQ_EVENTS_TYPEBOT_CHANGE_STATUS: "false"
      WEBSOCKET_ENABLED: "true"
      WEBSOCKET_GLOBAL_EVENTS: "true"
      WA_BUSINESS_TOKEN_WEBHOOK: evolution
      WA_BUSINESS_URL: https://graph.facebook.com
      WA_BUSINESS_VERSION: v18.0
      WA_BUSINESS_LANGUAGE: pt_BR
      SQS_ENABLED: "false"
      SQS_ACCESS_KEY_ID: ""
      SQS_SECRET_ACCESS_KEY: ""
      SQS_ACCOUNT_ID: ""
      SQS_REGION: ""
      WEBHOOK_GLOBAL_URL: ""
      WEBHOOK_GLOBAL_ENABLED: "false"
      WEBHOOK_GLOBAL_WEBHOOK_BY_EVENTS: "false"
      WEBHOOK_EVENTS_APPLICATION_STARTUP: "false"
      WEBHOOK_EVENTS_QRCODE_UPDATED: "true"
      WEBHOOK_EVENTS_MESSAGES_SET: "true"
      WEBHOOK_EVENTS_MESSAGES_UPSERT: "true"
      WEBHOOK_EVENTS_MESSAGES_UPDATE: "true"
      WEBHOOK_EVENTS_MESSAGES_DELETE: "true"
      WEBHOOK_EVENTS_SEND_MESSAGE: "true"
      WEBHOOK_EVENTS_CONTACTS_SET: "true"
      WEBHOOK_EVENTS_CONTACTS_UPSERT: "true"
      WEBHOOK_EVENTS_CONTACTS_UPDATE: "true"
      WEBHOOK_EVENTS_PRESENCE_UPDATE: "true"
      WEBHOOK_EVENTS_CHATS_SET: "true"
      WEBHOOK_EVENTS_CHATS_UPSERT: "true"
      WEBHOOK_EVENTS_CHATS_UPDATE: "true"
      WEBHOOK_EVENTS_CHATS_DELETE: "true"
      WEBHOOK_EVENTS_GROUPS_UPSERT: "true"
      WEBHOOK_EVENTS_GROUPS_UPDATE: "true"
      WEBHOOK_EVENTS_GROUP_PARTICIPANTS_UPDATE: "true"
      WEBHOOK_EVENTS_CONNECTION_UPDATE: "true"
      WEBHOOK_EVENTS_LABELS_EDIT: "true"
      WEBHOOK_EVENTS_LABELS_ASSOCIATION: "true"
      WEBHOOK_EVENTS_CALL: "true"
      WEBHOOK_EVENTS_NEW_JWT_TOKEN: "false"
      WEBHOOK_EVENTS_TYPEBOT_START: "false"
      WEBHOOK_EVENTS_TYPEBOT_CHANGE_STATUS: "false"
      WEBHOOK_EVENTS_CHAMA_AI_ACTION: "false"
      WEBHOOK_EVENTS_ERRORS: "false"
      WEBHOOK_EVENTS_ERRORS_WEBHOOK: ""
      CONFIG_SESSION_PHONE_CLIENT: EvolutionAPI
      CONFIG_SESSION_PHONE_NAME: Chrome
      QRCODE_LIMIT: 30
      QRCODE_COLOR: "#198754"
      TYPEBOT_API_VERSION: latest
      TYPEBOT_KEEP_OPEN: "false"
      CHATWOOT_MESSAGE_DELETE: "false"
      CHATWOOT_MESSAGE_READ: "false"
      CHATWOOT_IMPORT_DATABASE_CONNECTION_URI: postgres://user:password@hostname:port/dbname?sslmode=disable
      CHATWOOT_IMPORT_DATABASE_PLACEHOLDER_MEDIA_MESSAGE: "true"
      CACHE_REDIS_ENABLED: "false"
      CACHE_REDIS_URI: redis://redis:6379
      CACHE_REDIS_PREFIX_KEY: evolution
      CACHE_REDIS_TTL: 604800
      CACHE_REDIS_SAVE_INSTANCES: "false"
      CACHE_LOCAL_ENABLED: "false"
      CACHE_LOCAL_TTL: 604800
      AUTHENTICATION_TYPE: apikey
      AUTHENTICATION_API_KEY: a076c914af55d544fbf529032ed07197f91499008488c8af07550fe467376829
      AUTHENTICATION_EXPOSE_IN_FETCH_INSTANCES: "true"
      AUTHENTICATION_JWT_EXPIRIN_IN: 0
      AUTHENTICATION_JWT_SECRET: 'L=0YWt]b2w[WF>#>:&E`'
      LANGUAGE: en

volumes:
  evolution_instances:
  evolution_store:

networks:
  evolution-net:
